# Generated by Django 5.1.3 on 2024-11-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_city_options_alter_customuser_fav_cities"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_image/"),
        ),
    ]
